language: python
python:
- 2.7
install:
- pip install pytest
- pip install argparse
- pip install setuptools
- pip install enum
- pip install code-cov
before_install:
  - chmod +x setup.py
script:
- ./setup.py test
